### ISSUE TITLE
Postgres. role "root" does not exist.

### ISSUE THREAD

**Issue by I-am-PUID-0** [I-am-PUID-0/DMB#40]

**Comment by lukemuller** [comment]
I think you might have to pass `-U ${postgres_user}` to the `pg_isready` command (will need to also add the `postgres_user` to the `check_postgresql_started` param to be passed down)

https://github.com/I-am-PUID-0/DMB/blob/7154d239b10791068784fb144490960441a83501/utils/postgres.py#L90

Based on this: https://github.com/peter-evans/docker-compose-healthcheck/issues/16
