### ISSUE TITLE
Riven backend error

### ISSUE THREAD

**Issue by mladen100janovic** [I-am-PUID-0/DMB#94]
Hi, i ve got error  [Errno 111] Connection refused
so this is i think Riven Backend,i tried to change IP like in logs,(leave it as is also)add port 8080,no matter what i tried i got connection refused,btw i can access Ip of frontend where it asks for backed HTTP and Api from logs.

[DMB_logs (1).txt](https://github.com/user-attachments/files/18096496/DMB_logs.1.txt)
[docker-compose.txt](https://github.com/user-attachments/files/18096499/docker-compose.txt)

**Comment by mladen100janovic** [comment]
resolved

**Comment by FabioEight** [comment]
Hey @mladen100janovic , mind to share how you solved this?
